### ISSUE TITLE
[Enhancement] => Report on Auto-Awesome Module

### ISSUE THREAD

**Issue by netzerospace** [0xInfection/TIDoS-Framework#65] opened 2019-02-21 00:02 UTC
i run the The Auto-Awesome Module 

the screen keep clear-in out and i cant see the result

**Comment by 0xInfection** [comment] 2019-03-13 06:06
This version of TIDoS is very basic. I'm working on v2 of this framework, you'll find everything there. Until then... ;)

**Comment by 0xInfection** [comment] 2019-04-19 10:00
Closing this a duplicate of #69.

**Closed by 0xInfection** 2019-04-19 10:00 UTC
Labels: enhancement, question
