### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: b'liblibc.a'

### ISSUE THREAD

**Issue by elig0n** [0xInfection/TIDoS-Framework#130] opened 2021-02-07 12:30 UTC
**Describe the bug**
when running `list scan` or `list osint-active` this exception is raised:

```
@ tid2 > list scan
Traceback (most recent call last):
  File "/TIDoS-Framework/tidconsole.py", line 782, in <module>
    main()
  File "/TIDoS-Framework/tidconsole.py", line 777, in main
    TIDcon().cmdloop()
  File "/TIDoS-Framework/tidconsole.py", line 52, in cmdloop
    super(TIDcon, self).cmdloop(intro=None)
  File "/usr/lib/python3.9/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.9/cmd.py", line 217, in onecmd
    return func(arg)
  File "/TIDoS-Framework/tidconsole.py", line 335, in do_list
    select.list(inp,True)
  File "/TIDoS-Framework/core/methods/select.py", line 219, in list
    j = imp.import_module(module2)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/TIDoS-Framework/modules/ScanningEnumeration/0x01-PortScanning/finscan.py", line 13, in <module>
    from scapy.all import *
  File "/usr/lib/python3.9/site-packages/scapy/all.py", line 16, in <module>
    from scapy.arch import *
  File "/usr/lib/python3.9/site-packages/scapy/arch/__init__.py", line 27, in <module>
    from scapy.arch.bpf.core import get_if_raw_addr
  File "/usr/lib/python3.9/site-packages/scapy/arch/bpf/core.py", line 30, in <module>
    LIBC = cdll.LoadLibrary(find_library("libc"))
  File "/usr/lib/python3.9/ctypes/util.py", line 330, in find_library
    _get_soname(_findLib_gcc(name)) or _get_soname(_findLib_ld(name))
  File "/usr/lib/python3.9/ctypes/util.py", line 147, in _findLib_gcc
    if not _is_elf(file):
  File "/usr/lib/python3.9/ctypes/util.py", line 99, in _is_elf
    with open(filename, 'br') as thefile:
FileNotFoundError: [Errno 2] No such file or directory: b'liblibc.a'
```

 - OS: Arch linux
 - Python Version 3.9
 - TIDoS Version git

**Comment by stuffi27** [comment] 2021-02-07 14:46
Hi had the same problem, and than the next problem and the next and so on. error line 27, 56, etc. etc. under my Kali Linux, 2021. TiDoS just didn't work properly and it crashed. Until I've looked at every single line. in my oppinion the problem is fixed by upgrading all of beautifulsoup4, html5lib, and lxml.

ttidos has been working since I fixed the the problem on my kali. Try it please give feedback.
 
please do this -->

sudo pip install --upgrade beautifulsoup4 && sudo pip install --upgrade html5lib && sudo pip3 install html5lib==0.9999999 && sudo pip install html5lib==0.9999999 && sudo apt remove python3-bs4 python3-html5lib && sudo apt install python3-bs4 python3-htmllib && sudo pip install spry && sudo pip install --upgrade html5lib==1.0b8 && pip install --upgrade bs4 && sudo pip install --upgrade bleach==1.4.2 && sudo pip install --upgrade lxml

**Comment by elig0n** [comment] 2021-02-08 00:40
The above solution did not work for me. 
Eventually I solved it by:
`ln -sr libc.a liblibc.a`
under /usr/lib/
(based on [this solution](https://stackoverflow.com/questions/65410481/filenotfounderror-errno-2-no-such-file-or-directory-bliblibc-a))

**Closed** 2021-02-08 00:40 UTC
Labels: bug
