### ISSUE TITLE
[Bug] => Unhandled exception on some modules

### ISSUE THREAD

**Issue by RemakingEden** [0xInfection/TIDoS-Framework#59] opened 2018-11-30 09:39 UTC
Hi @0xInfection,

Thanks for the framework, I'm really enjoying working with it so far.

I'm new to Github and leaving issues so forgive me if I do anything wrong/miss anything off this report. I have seen on other issues you have requested debug info on the modules. I'm not entirely sure how to do this, however, I will give everything I can.

My system is Linux Mint and my Python version is Python 2.7.15rc1

The modules I am having an issue with are: (All of these come from using the Auto awesome feature)
```
   =====================================
    R E V E R S E   D N S   L O O K U P
   =====================================

 [!] Looking Up for Reverse DNS Info...
 [~] Result: 

 [-] Unhandled runtime exception while execution...
 [-] Exception Encountered: list index out of range
 [-] Returning back to main menu...
```
    
```
     ==================================
      G R A B   H T T P   H E A D E R S
     ===================================

 [!] Grabbing HTTP Headers...
 [-] Unhandled runtime exception while execution...
 [-] Exception Encountered: 'module' object has no attribute 'HTTPError'
 [-] Returning back to main menu...
```
```
    ================================
     HTTP STRICT TRANSPORT SECURITY
    ================================

 [*] Configuring headers...
 [*] Got any cookies? [just enter if none] :> 
 [*] Making the request...
 [-] Unhandled runtime exception while execution...
 [-] Exception Encountered: local variable 'flag' referenced before assignment
 [-] Returning back to main menu...
```

I'm also finding that when the error occurs none of the previous info is saved so the /opt/tidos/tmp/criteo.com-subdomains.lst is blank and there is nothing at all in /opt/tidos/tmp/logs/criteo.com-logs.

If I find any more I will add them, let me know if there is other info you need from me.

**Comment by 0xInfection** [comment] 2018-11-30 10:10
Thank you for raising this issue. I was always looking for these kinda issues. I'll push a patch within today. And yeah, if there are more, just bring them on. It will be a good fixing them.

**Comment by 0xInfection** [comment] 2018-11-30 12:04
Alright have a look at #60. These 3 bugs have been tested and fixed. You can try cloning the [Fixing-#59](https://github.com/0xInfection/TIDoS-Framework/tree/Fixing-%2359) branch and tell me if the issue still has been fixed or not. 🙂

**Comment by 0xInfection** [comment] 2018-11-30 12:33
Oh shit, I forgot to revert the test environments. Fixed it. Try `git pull` and run `tidos.py` file. No need to run the install file over again.

**Comment by RemakingEden** [comment] 2018-11-30 13:32
Seems to be fixed. I won't have time to have a decent look until tomorrow but I will update when i'm sure. Thanks again!

**Comment by RemakingEden** [comment] 2018-11-30 18:14
All the past ones seem to be working now. I have found ana new issue. Linked below.

**Comment by RemakingEden** [comment] 2018-11-30 18:17
![criteo com-dnsmap](https://user-images.githubusercontent.com/12913562/49307123-3a866180-f50f-11e8-953f-bea3659ff9a4.jpg)
The DNS map also does not appear to be working/opening. Would you like me to start a new bug for this?

**Comment by 0xInfection** [comment] 2018-12-01 06:55
I found the SQLi issue in both Auto Awesome modules. They will be worked on.

__Update:__ Alright, all these issues has been fixed in the above 5 commits, some have improved a lot in their functionality too! 💜

**Comment by 0xInfection** [comment] 2018-12-03 06:49
Will be fixed within today. :)

**Comment by 0xInfection** [comment] 2018-12-08 18:59
I guess everything has been working as intended. So yeah, for now I am closing this as fixed. Since, this fixes a lot of bugs, I wouldn't like the PR to be hanging. So yeah, thank you so much for your contribution. If you find some other bugs out there, just don't hesitate to pull up an issue.

**Closed** 2018-12-08 18:59 UTC
Labels: bug, enhancement, on the go

**Comment by RemakingEden** [comment] 2019-01-12 11:36
> I guess everything has been working as intended. So yeah, for now I am closing this as fixed. Since, this fixes a lot of bugs, I wouldn't like the PR to be hanging. So yeah, thank you so much for your contribution. If you find some other bugs out there, just don't hesitate to pull up an issue.

Thanks mate, ive lost all my time since moving to Japan. If I get some more time I will look over everything again :)
